Only source configuration files that end with the '.conf' extension.
Thanks to @nrgaway for the suggestion!

https://phabricator.whonix.org/T286

diff --git a/usr/lib/ram_adjusted_desktop_starter/display-manager-dpkg-post-invoke b/usr/lib/ram_adjusted_desktop_starter/display-manager-dpkg-post-invoke
--- a/usr/lib/ram_adjusted_desktop_starter/display-manager-dpkg-post-invoke
+++ b/usr/lib/ram_adjusted_desktop_starter/display-manager-dpkg-post-invoke
@@ -27,27 +27,14 @@ else
     true "$BASH_SOURCE INFO: Script running as root."
 fi
 
-for i in /etc/rads.d/*; do
-   if [ -f "$i" ]; then
-      ## If the last character is a ~, ignore that file,
-      ## because it was created by some editor,
-      ## which creates backup files.
-      if [ "${i: -1}" = "~" ]; then
-         continue
-      fi
-      ## Skipping files such as .dpkg-old and .dpkg-dist.
-      if ( echo "$i" | grep -q ".dpkg-" ); then
-         true "skip $i"
-         continue
-      fi
-      bash_n_exit_code="0"
-      bash -n "$i" || { bash_n_exit_code="$?" ; true; };
-      if [ ! "$bash_n_exit_code" = "0" ]; then
-         echo "$BASH_SOURCE ERROR: invalid rads config file $i." >&2
-         exit 1
-      fi
-      source "$i"
+for i in /etc/rads.d/*.conf; do
+   bash_n_exit_code="0"
+   bash -n "$i" || { bash_n_exit_code="$?" ; true; };
+   if [ ! "$bash_n_exit_code" = "0" ]; then
+      echo "$BASH_SOURCE ERROR: invalid rads config file $i." >&2
+      exit 1
    fi
+   source "$i"
 done
 
 if [ ! "$rads_autostart_decision_feature" = "1" ]; then
